version: '3'

services:
  portfolioDockerImage:
    build: .

    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - PROD_API_URL=http://ec2-54-67-67-2.us-west-1.compute.amazonaws.com
